title: "Pythonで2Dゲームをかじる本(Tkinter編)"
summary: "
Python標準ライブラリ「Tkinter」を使って、2Dゲーム制作をかじってみる連載です。
スプライト管理やマウス入力など、ゲームの基本要素を、
Pythonの基礎的なコードだけで少しずつ作っていきます。
"
topics: ["python", "python3", "初心者向け","tkinter","ゲーム開発"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap01
  - chap02
  - chap03
  - chap04
  - chap05
  - chap06
  - chap07
  - chap08
  - chap09
  - chap10
