title: "Python3をかじる本"
summary: "
Python3を\"ちょっとだけかじってみたい人\"のための入門書です。\n
Python3の環境づくりから、基本的な文法、動作確認までをできるだけ簡単にまとめます。\n
\n
1, プログラミングやってみたいな😀!!\n
2, Pythonって何? 蛇!? 怖い😭!!\n
3, 難しいことは置いといて、ノリで動かしたい☺️!!\n
\n
そんなあなたにぴったりの内容です。
"
topics: ["python", "python3", "初心者向け"]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap01
  - chap02
  - chap03
  - chap04
  - chap05
  - chap06
  - chap07
  - chap08-1
  - chap08-2
  - chap09
  - chap10
  - chap11
  - chap12
  - chap13