title: "Pythonをかじる本(甘噛み編)"
summary: "
Pythonを\"かじってみたい人\"のための入門書です。\n
プログラミング初学者向けに、基本的な文法、動作確認までをできるだけ簡単にまとめます。\n
\n
1, プログラミングやってみたい...でも怖い😭\n
2, Pythonって何? 蛇!? ...やだ怖い😭\n
3, 難しいことは置いといて、動かして...けど怖い☺️\n
\n
そんなあなたの\"甘噛みPython入門書\"です。
"
topics: ["python", "python3", "初心者向け"]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap01
  - chap02
  - chap03
  - chap04
  - chap05
  - chap06
  - chap07
  - chap08-1
  - chap08-2
  - chap09
  - chap10
  - chap11
  - chap12
  - chap13
  - chap14