title: "Python3をかじる本"
summary: "
Python3を\"ちょっとだけかじってみたい人\"のための入門書です。\n
Python3の環境づくりから、基本的な文法、動作確認までをできるだけ簡単にまとめます。\n
\n
1, 難しいことは置いといて、まず触りたい!!\n
2, サクッとPython3の雰囲気を味わいたい!!\n
3, コスパ良く要点だけ知りたい!!\n
\n
そんなあなたにぴったりの内容です。
"
topics: ["python", "python3", "初心者向け"]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap1
  - chap2
  - chap3
  - chap4
  - chap5
  - chap6
  - chap7
  - chap8-1
  - chap8-2
  - chap9
