title: "Python3をかじる本"
summary: "
Python3を\"ちょっとだけかじってみたい人\"のための入門書です。\n
Python3の紹介や環境づくりから、基本の文法、動作確認までをできるだけゆるくまとめました。\n
\n
1, 難しいことは置いといて、まず触りたい!!\n
2, サクッとPython3の雰囲気を味わいたい!!\n
3, ガチガチより、ちょっと変わった入門書が好き!!\n
\n
そんなあなたにぴったりの内容です。
"
topics: ["python3", "初心者向け"]
published: false
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - page1
  - page2
  - page3
