title: "Pythonで2Dゲームをかじる本(Arcade基礎編)"
summary: "
Pythonのゲーム専用ライブラリ「Python Arcade Library」を使って、2Dゲーム制作をかじってみる連載です。
スプライト管理やキーボード入力、サウンド再生といったゲームの基本要素を、
Pythonの基礎的なコードだけで少しずつ作っていきます。
(執筆時点でのバージョンはv3.3.3です)"
topics: ["python", "python3", "arcade", "初心者向け", "ゲーム開発"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chap01
  - chap02
  - chap03
  - chap04
  - chap05
  - chap06
  - chap07
  - chap08
  - chap09
  - chap10
  - chap11
  - chap12
  - chap13
